const { authenticator } = require("otplib");
const QRCode = require("qrcode");

// IMPORTANT CONCEPTUAL DIFFERENCE FROM EMAIL/SMS OTP:
//
// Email and SMS OTP (otpService.js) work with a "challenge": a one-time
// code generated by OUR server, stored as a hash, checked once, then
// thrown away. There's no concept of that here.
//
// TOTP (Time-based One-Time Password) - what authenticator apps like
// Google Authenticator use - works differently: the user's app and our
// server both know a shared SECRET (generated once, during setup). Both
// sides independently compute a 6-digit code from that secret combined
// with the current time, refreshed every 30 seconds. Nobody "sends" a
// code anywhere - the user's app just displays whatever it currently
// computes, and our server re-computes the same thing to check it.
//
// This is why there's no challengeId, no expiresAt, no "resend" here -
// the secret is long-lived (as long as MFA stays enabled), and
// verification is just "does this code match what the secret produces
// right now" (with a small tolerance window for clock drift).

// Generates a brand new TOTP secret for a user, and a QR code image
// (as a data URL the frontend can put straight into an <img> tag)
// encoding that secret in the standard otpauth:// format that
// authenticator apps understand.
async function generateMfaSetup(userEmail) {
  const secret = authenticator.generateSecret();

  const otpauthUrl = authenticator.keyuri(userEmail, "SecureID", secret);

  const qrCodeDataUrl = await QRCode.toDataURL(otpauthUrl);

  return {
    secret, // stored on the user record, NOT sent anywhere except this response
    qrCodeDataUrl,
  };
}

// Checks a 6-digit code the user typed against their stored secret.
// authenticator.check() allows a small time-drift tolerance by default
// (checks the current 30-second window plus one before/after), which is
// standard behavior - it's why authenticator apps still work even if
// your phone's clock is a few seconds off from the server's.
function verifyTotpCode(secret, code) {
  try {
    return authenticator.check(code, secret);
  } catch (error) {
    // otplib throws if the code isn't a valid-looking token (e.g. wrong
    // length) rather than just returning false - we treat that the same
    // as "wrong code" rather than crashing the request.
    return false;
  }
}

module.exports = {
  generateMfaSetup,
  verifyTotpCode,
};
